# basic setup
baseURL = 'https://blog.ingtshan.top/'
## [en, zh-cn, fr, ...]
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
## 是否包括中日韩文字
hasCJKLanguage = true
# ui
title = "熒的文字"
theme = "PaperMod"
